language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  fast_finish: true
  include:
    - php: 7.3
    - php: 7.4
    - php: 8.0

before_script:
  - composer self-update
  - echo "memory_limit=3G" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

install: composer install --dev

script: phpunit --coverage-clover clover

after_success:
    - curl -sL https://bit.ly/artifact-uploader | php
